### ISSUE TITLE
Dataset directory structure.

### ISSUE THREAD

**Issue by jjdredd** [MaliParag/ScanSSD#2]
I want to train the model, but `train.py` seems to expect a dataset directory structure different
from the one in the dataset https://github.com/MaliParag/TFD-ICDAR2019 (mentioned in the readme). For example, it expects bounding boxes for each image (each page) to be in a separate
csv file with extension `.pmath`, while the above mentioned repo contains the dataset with annotations for ALL the pages in each document in one csv file (per pdf document).
Is it true or did I make a mistake reading code and missed something obvious?

Here's a script I made to transform the dataset into the required format:

https://github.com/jjdredd/TFD-ICDAR2019/blob/master/TFD-ICDAR2019v2/create_datasets.py

**Comment by MaliParag** [comment]
Hi, Yes it is true. 

You can use this script to do that: https://github.com/MaliParag/ScanSSD/blob/master/gtdb/split_annotations_per_page.py

**Comment by jjdredd** [comment]
Oh, sorry. I guess I missed those tools. Thanks!
Does the training script expect normalized box coordinates?

**Comment by MaliParag** [comment]
No, it does not. Some cleanup is required in that script.

I have added [annotations](https://github.com/MaliParag/ScanSSD/tree/master/annotations
) in the repo, so that it is easier for people to use it without having to go through setting up annotations directory.

Feel free to use that.

**Comment by jjdredd** [comment]
Thanks much!
