### ISSUE TITLE
Missing file while stitching the patch level results？

### ISSUE THREAD

**Issue by LiKun-DLUT** [MaliParag/ScanSSD#4]
Hi, I'm trying to get the test results using the pre-trained model. When I run stitch_patches_pdf.py to  stitching the patch level results, I don't understand the parameter --data_file <Workspace>/train_pdf.  Does it mean I need a PDF file? Is there any file missing in the project?

**Comment by MaliParag** [comment]
train_pdf is just a file with pdf filenames, one filename per line. If you have 36 files for training there will be 36 lines and each line will have one filename.

**Comment by MaliParag** [comment]
Added for reference - https://github.com/MaliParag/ScanSSD/blob/master/train_pdf
