### ISSUE TITLE
Please specify model type for pretrained weights.

### ISSUE THREAD

**Issue by jjdredd** [MaliParag/ScanSSD#5]
Thank you for providing pretrained weights. Please  indicate model_type, cfg, kernel and
padding for the pretrained model.

**Comment by huangtao36** [comment]
I'd like to know too. Please.
I got an error:
```
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.loc.0.weight: copying a param with shape torch.Size([28, 512, 1, 5]) from checkpoint, the shape in current model is torch.Size([28, 512, 1, 1]).
	size mismatch for module.loc.1.weight: copying a param with shape torch.Size([28, 1024, 1, 5]) from checkpoint, the shape in current model is torch.Size([28, 1024, 1, 1]). ... ...
```

**Comment by jjdredd** [comment]
@huangtao36 I was able to test the model using the following parameters with pretrained weights:

https://github.com/jjdredd/ScanSSD/blob/4e10f4d433e1648e5a1ce37c2fb7a136ce4c0122/detect.py#L18

But I'd still like to hear from the original author because it's just my guess.

**Comment by MaliParag** [comment]
You should be able to use the following command for testing with pre-trained weights 
 
python3 /home/psm2208/Workspace/ssd/test.py --dataset_root /home/psm2208/Workspace/ --trained_model AMATH512_e1GTDB.pth --visual_threshold 0.25 --cuda True --exp_name test_MATH512 --test_data validation_data  --suffix "_512" --model_type 512 --cfg hboxes512 --padding 0 2 --kernel 1 5 --batch_size 8
